print("This python file is in the main branch.")
print("With git, try to:")
print("- clone this repository onto your system")
print("- make a branch")
print("- add a new file to that branch")
print("- push the changes back to github with a meaningful commit message")
print("- try doing the same thing with github desktop")
